import type { HubConfig, MCPConfig } from "./types.js";
import { buildGitignoreLines } from "./claude-code-plan.js";
import type { EditorPlan } from "./plan-types.js";
import { buildCodexMcpBlock } from "./codex-config.js";
import {
  buildOrchestratorRule,
  buildProxyUpstreams,
  getUpstreamNames,
} from "./prompt-builders.js";

export function buildCodexConfigToml(config: HubConfig): { toml: string; warnings: string[] } | null {
  if (!config.mcps?.length) return null;

  const warnings: string[] = [];
  const upstreamSet = getUpstreamNames(config.mcps);
  const blocks: string[] = [
    "# GENERATED by `hub generate -e codex` from hub.yaml — do not edit by hand.",
    "#",
    "# Codex only loads this file when the project is trusted:",
    "#   codex projects trust",
    "# AGENTS.md and skills/ are read natively and do not need extra config here.",
    "",
  ];

  for (const mcp of config.mcps) {
    if (upstreamSet.has(mcp.name)) continue;
    let resolved: MCPConfig = mcp;
    if (mcp.upstreams?.length) {
      const { upstreamsJson, collectedEnv } = buildProxyUpstreams(mcp, config.mcps);
      resolved = { ...mcp, env: { MCP_PROXY_UPSTREAMS: upstreamsJson, ...collectedEnv } };
    }
    const result = buildCodexMcpBlock(mcp.name, resolved);
    if (result === null) {
      warnings.push(`Skipping MCP "${mcp.name}": no url, image, or package configured`);
      continue;
    }
    warnings.push(...result.warnings);
    blocks.push(result.block, "");
  }

  return {
    toml: blocks.join("\n").replace(/\n{3,}/g, "\n\n").trimEnd() + "\n",
    warnings,
  };
}

export function planCodexFiles(config: HubConfig): EditorPlan {
  const files: EditorPlan["files"] = [];
  const warnings: string[] = [];

  const orchestratorRule = buildOrchestratorRule(config);
  const cleanedOrchestrator = orchestratorRule.replace(/^---[\s\S]*?---\n/m, "").trim();
  files.push({ path: "AGENTS.md", content: cleanedOrchestrator + "\n", kind: "file" });

  const toml = buildCodexConfigToml(config);
  if (toml) {
    files.push({ path: ".codex/config.toml", content: toml.toml, kind: "file" });
    warnings.push(...toml.warnings);
  }

  files.push({ path: ".gitignore", content: buildGitignoreLines(config).join("\n"), kind: "managed-block" });

  return { files, warnings };
}
